AWSTemplateFormatVersion: '2010-09-09'
Description: 'this is first even template'
Resources:
  cfvm:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: 'us-east-1a'
      ImageId: "ami-0bd6d37f25afa4d5a"
      InstanceType: !Ref InstanceTypeParameter
      KeyName: "june2021"
      SecurityGroupIds:
      - sg-0018114de75d0a639
      Tags:
      - Key: Name 
        Value: cfvm
Parameters:
  InstanceTypeParameter:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - m1.small
      - m1.large
    Description: Enter t2.micro, m1.small, or m1.large. Default is t2.micro.
